README.md

Sorry for the noise. It turns out providing the url is only sufficient in the `pkg>` REPL mode. If using `using Pkg` one has to specify a `PackageSpec`

Actually working installation commands

---

README.md

The readme in its current form was a bit sprawling and hard to manage. I made sections of it collapsible so it is easier to navigate and get an overview. An alternative approach would be a table of contents. 
I also added a section called "Dealing with structs" where I recommend `StructArrays.jl` for kernels involving unsupported number types and demo it with that gemm kernel I posted on discourse.

Overhaul README with collapsible sections and add section discussing structs

---

Manifest.toml
Project.toml
src/LoopVectorization.jl
src/add_loads.jl
src/graphs.jl
src/reconstruct_loopset.jl
src/vectorizationbase_extensions.jl
test/dot.jl
test/gemv.jl
test/offsetarrays.jl
test/runtests.jl

This supports syntax like
```julia
for i in iter
end
```
Because `iter` could be a `CartesianIndex` I presume we have to treat it the same way `eachindex(A)` gets treated.
Some of this is just whitespace changes (courtesy of Atom), but you can select to ignore it when reviewing. Also note I added a couple of `using` statements at the top of test files to facilitate running them independently. If you don't like that I can remove that part.

Fix `for i in iter`

---

docs/make.jl
docs/src/api.md
src/LoopVectorization.jl
src/broadcast.jl
src/constructors.jl
src/costs.jl
src/filter.jl
src/map.jl

Other than `_avx_!`, every export is documented including `LoopVectorization` itself. (I don't always remember, but I often like to provide a brief API summary of a package in the module's docstring). It also adds a new API reference page to the Documenter docs. 
Sorry about the whitespace changes, my Atom settings do it automatically.

Add a few more docstrings

---

docs/Manifest.toml
docs/Project.toml
docs/make.jl
docs/src/devdocs/constructing_loopsets.md
docs/src/devdocs/evaluating_loops.md
docs/src/devdocs/loopset_structure.md
src/costs.jl

The new devdocs are wonderful! They are really helping me get a better handle on the internals.
These are a few tweaks that helped clarify my thinking, but different folks might think differently. Feel free to close this if you think it's a step backwards.
The change to the `prettyurls` setting makes it easier to browse the docs in a local build. I also added `[compat]` bounds on Documenter because I've had my docs break when new releases are made.
One thing I was intrigued by is where the costs come from. I tried to put in one reference, but if you prefer another one by all means use it instead. And I'm pretty vague on what the register pressure is actually measuring (what are its units?), and didn't even try on the `scaling` parameter.

Small tweaks to the devdocs

---

src/condense_loopset.jl
src/reconstruct_loopset.jl

Preserve names of arrays and iteration variables across generated boundary

---

.travis.yml
src/add_ifelse.jl
src/condense_loopset.jl
src/lower_load.jl
src/lower_store.jl
src/memory_ops_common.jl
src/reconstruct_loopset.jl
test/miscellaneous.jl

ImageFiltering contains optimizations for separable filters: if the filter size along each dimension is `n[i]`, then per-pixel a fully-separable filter has cost `O(n[1] + ... + n[d])`, where as a non-separable filter has cost `O(n[1] * ... * n[d])`. Consequently this can be a very large savings. This PR aims to support such operations by extending support for the exponential-filter demo in https://julialang.org/blog/2016/02/iteration/.
This doesn't yet work, because I haven't yet compensated for what the commented-out `@assert` is supposed to catch. I thought I'd submit this now to discuss the right architecture changes. My presumption is that the easiest approach is to return `Δidxs` from `calcnops` and thus make `nopsv` a `Vector{Vector{Int}}`. But if you have a better suggestion I am …

WIP: support mixed Int/CartesianIndex indexing

---

Project.toml
docs/make.jl
docs/src/api.md
docs/src/devdocs/reference.md
src/LoopVectorization.jl
src/condense_loopset.jl
src/constructors.jl
src/costs.jl
src/operations.jl
src/reconstruct_loopset.jl
test/offsetarrays.jl

While most of this should hopefully be OK, notice that I've embedded a number of questions where I am uncertain of the answer. It would be best to resolve or delete these questions before merging. @chriselrod, you are authorized to just edit the files or answer here and I will make changes.
One oddity: Documenter complains about not being able to find the docstring for `LoopVectorization.vfilter!` and then later complains that we didn't put it in a `@docs` block. I am confused by this.
Hope the additional dependency on DocStringExtensions is OK. If not, we can delete it.

Add more documentation on the internals

---

Project.toml
src/determinestrategy.jl
src/mapreduce.jl
test/mapreduce.jl

Fix #110
```julia
julia > using LoopVectorization, BenchmarkTools
julia> x = rand(Float32, 128, 128)
julia> @btime(vreduce($max, $x)) ≈ @btime(maximum($x))
492.268 ns (0 allocations: 0 bytes)
9.903 μs (0 allocations: 0 bytes)
true
julia> @btime(vreduce($min, $x)) ≈ @btime(minimum($x))
493.273 ns (0 allocations: 0 bytes)
9.905 μs (0 allocations: 0 bytes)
true
julia> @btime(vreduce($+, $x)) ≈ @btime(sum($x))
492.242 ns (0 allocations: 0 bytes)
1.977 μs (0 allocations: 0 bytes)
true
julia> for d in 1:ndims(x)
println("dims: $d")
@assert @btime(vreduce($max, $x; dims = $d)) ≈ @btime(maximum($x; dims = $d))
@assert @btime(vreduce($min, $x; dims = $d)) ≈ @btime(minimum($x; dims = $d))
@assert @btime(vreduce($+, $x; dims = $d)) ≈ @btime(sum($x; dims = $d))
end
dims: 1
1.938 μs (6 allocations: …
```

Vreduce along a single dimension

---

test/runtests.jl

Fixes #160 
Right now, if the test suite starts to take a really long time to run, we have no way of noticing (unless we happen to open up the test log).
This pull request adds a single test to the end of the test suite. This test will:
- PASS if the test suite takes two hours or less 
- FAIL if the test suite takes more than two hours
We can certainly change this limit. I picked two hours because, as far as I can tell, none of the jobs take more than 1.5 hours to run.

Add a test that will fail if the test suite takes more than two hours

---

Project.toml
src/graphs.jl
test/miscellaneous.jl

This replaces `println(ex); throw(str)` with an error type, so that if macro expansion fails within a try-catch block, nothing is printed. 
Closes https://github.com/mcabbott/Tullio.jl/issues/26
Example of new behaviour:
```
julia> try                                                                   
macroexpand(Main, quote                                               
@avx for i = 𝒶𝓍i                                                      
if i ∈ (axes)(var"𝛥≪rand(10)≫", 1)                                
var"𝛥≪rand(10)≫"[i] = var"𝛥≪rand(10)≫"[i] + 𝛥ℛ[i]             
else                                                              
(zero)((eltype)(var"𝛥≪rand(10)≫"))                            
end                                                               
end …
```

Remove `println` statements accompanying errors

---

test/runtests.jl

On the most recent commit to `master`, one job took [2h 20m 9s](https://github.com/chriselrod/LoopVectorization.jl/runs/1545836570) and another job took [2h 12m 46s](https://github.com/chriselrod/LoopVectorization.jl/runs/1546008232).
So let's increase the limit from two hours to three hours.
(In the commit message, I wrote "two hours to four hours", which is a typo. As seen in the diff, the actual change in "two hours to three hours".)

Increase the `ELAPSED_MINUTES` test limit from two hours to three hours

---

README.md
docs/src/examples/array_interface.md
docs/src/examples/matrix_multiplication.md
docs/src/examples/matrix_vector_ops.md

Since some users (e.g. macOS users with only the default system fonts) might not be able to render the subscripts.

Docs only: Replace Unicode subscript i (resp. j, l, m, n, s) with _i (resp. _j, _l, _m, _n, _s)

---

README.md

According to CI, the package is currently tested on the latest 1.x release (currently 1.5.4), 1.5.4 explicitly (redundant?) and nightly. However, the README.md says that Julia 1.1 and 1.3 are tested, which doesn't seem to be true. In this PR I update the corresponding line.
Feel free to edit further or close the PR if I misunderstood something.

Update tested Julia versions in README.md

---

src/simdfunctionals/vmap_grad.jl

If one bundle this package into a sysimage, it is quite easy to run into problems because the package will at Julia start time try to load `VectorizationBase` which will cause a full package lookup via the project and manifest of the currently active project. If one does not have a project active such that this is possible when Julia starts, it will error. There is actually no need for this, we can just use the VectorizationBase that is already loaded in the package.

tweak package import in file loaded by Requires

---

.github/workflows/ci-julia-nightly.yml
.github/workflows/ci.yml
src/condense_loopset.jl
test/arraywrappers.jl
test/check_empty.jl
test/loopinductvars.jl
test/runtests.jl
test/shuffleloadstores.jl
test/threading.jl
test/utils.jl

VectorizationBase.jl runs CI on macOS, since those machines are older and often don't have AVX2.
Would it make sense to do the same thing for LoopVectorization.jl?

Run CI on macOS (in addition to Linux and Windows)

---

README.md

I encountered an issue when using nested loops with multiple loops at the same level. This comment might help other users of this great package when running into such an issue. Did I understand the comment https://github.com/JuliaSIMD/LoopVectorization.jl/issues/230#issuecomment-810632972 correctly?

add another assumption of at-avx to the README.md

---

README.md

We're already using LoopVectorization to get some really nice improvements in our hyperbolic PDE framework. We will use LoopVectorization even more and also other great packages of yours like CheapThreads and StrideArrays once #238 (and maybe https://github.com/JuliaSIMD/VectorizationBase.jl/issues/53) are resolved.

add Trixi to users of LoopVectorization

---

src/simdfunctionals/map.jl

This might reduce confusion whether these threaded map versions work well with Octavian, cf. https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/80.

update docstrings to not point to Threads.at-threads anymore

---

Project.toml
src/LoopVectorization.jl
src/codegen/loopstartstopmanager.jl
src/codegen/lower_compute.jl
src/codegen/lower_threads.jl
src/codegen/lowering.jl
src/condense_loopset.jl
src/modeling/determinestrategy.jl
src/modeling/graphs.jl
src/parse/memory_ops_common.jl
src/reconstruct_loopset.jl
src/simdfunctionals/filter.jl
src/simdfunctionals/map.jl
src/simdfunctionals/vmap_grad.jl
src/vectorizationbase_compat/contract_pass.jl

On current master, they are passed in the stack.
This PR tries to pass them in registers instead.
Of course, this only matters when `_avx_!` isn't inlined.

Pass arguments to _avx_! in registers.

---

src/modeling/determinestrategy.jl

```
julia> @btime LoopVectorization.solve_unroll_lagrange(view($(ls.cost_vec),:,1), view($(ls.reg_pres),:,1), 1025, 1025, 1, 1, true) #before
330.934 ns (20 allocations: 480 bytes)
(3, 9, 1.055816625e8)
julia> @btime LoopVectorization.solve_unroll_lagrange(view($(ls.cost_vec),:,1), view($(ls.reg_pres),:,1), 1025, 1025, 1, 1, true) #after
131.151 ns (0 allocations: 0 bytes)
(3, 9, 1.055816625e8)
```

Optimize `solve_unroll_lagrange`

---

.codecov.yml
.github/workflows/ci-julia-nightly.yml
.github/workflows/ci.yml
Project.toml
test/runtests.jl

I observed that the CI tests take quite a while for LoopVectorization. I guess this can be annoying since you have to wait for several hours to see whether PRs pass all tests. Here, I propose to split the tests into three parts which can be run in parallel to reduce wall clock time for CI.
If this is acceptable, the required CI tests need to be updated.

parallel tests

---

docs/src/index.md

Sometimes, people will find the docs via Google etc. at first. Then, it canbe nice to have a link back to the repo on GitHub.

add link to the repo to the docs

---

Project.toml
src/broadcast.jl
src/codegen/lower_threads.jl
src/codegen/lowering.jl
src/condense_loopset.jl
src/constructors.jl
src/modeling/determinestrategy.jl
src/reconstruct_loopset.jl
test/shuffleloadstores.jl
test/special.jl

Also adds the option to choose which loop to vectorize. The primary motivation there is for cases where correctness depends on it, e.g. the hacky uses of vector operations like `vpermilps177`.
Bumps SLEEFPirates requirement, which fixes #307 
Allowing more than 256 operations should fix #305

Allow more than 256 operations in a loopset

---

Project.toml
src/reconstruct_loopset.jl

This method isn't necessary (it just replicates the fallback),
and it triggers ~600 invalidations.
CC @ChrisRackauckas

Delete `convert(::Type{Any}, ::UpperBoundedInteger)`

---

docs/make.jl
docs/src/examples/datetime_arrays.md
docs/src/index.md

- Add example documentation for DateTime vectors
- Based on #339
- Problem Overview
- Benchmarks showing 3x speedup with constant memory requirements
- Add new example doc to Documenter build step
- Add new example doc to "Manual Outline" on home page
Image previewing below.
---

Turbo over Vector of DateTimes

---

test/miscellaneous.jl

This is the default storage in JuliaImages. This ensures that methods
based on LoopVectorization will continue to work (an insurance policy
against future changes), and also makes it easy to check performance
(manually, since CI is bad for performance tests).
Currently, the performance on the RGB does not match the "in principle" 3x the corresponding grayscale. For a 3d output image of size 11x11x11, here are the timings I'm getting for filtering along a single dimension `d`:
| d | t grayscale (μs) | t RGB (μs) | Expected based on grayscale | `@simd` only |
| - | ----------:| -----------:| -----:| ----:|
| 1 | 4.5 | 27.5 | 13.5 | 42.2 |
| 2 | 1.8 | 14.1 | 5.4 | 48.5 |
| 3 | 1.1 | 5.2 | 3.3 | 48.8 |
Not sure if it's even fixable (meaning, we should switch to struct-of-arrays …

Add tests that mimic array-of-struct RGB

---

src/codegen/lower_memory_common.jl
src/codegen/lowering.jl

We need to check if this regresses quality somewhere, but if not, this
should speed up inference of LoopVectorization a fair bit.

WIP: Faster Inference

---

Project.toml
src/constructors.jl
test/grouptests.jl
test/parsing_inputs.jl

There are four macros which will generate loop whose body is not a block. The `gen_loop_issue395` and `gen_A_mul_B` macro cause `StackOverflowError` in current master while the `gen_single_loop` and `gen_nest_loop` cause `LoadError: TypeError: in typeassert, expected Int64, got a value of type Static.StaticInt{1}`. I have no idea about these errors, but warp those loop body as a block that fixes all of these error.

fix: #395, check if loop body is a block and warp it if not

---

src/constructors.jl
test/parsing_inputs.jl

I'm working on the issue #393 by replacing enumerate which can be integrated in the check of loop body. However, I have some difficulties.
First, turbo for a expression instead of a symbol may cause `LoadError` like:
```Julia
@turbo for i in 1:length(1:10)
n = (1:10)[i+firstindex(1:10)-1]
end
```
may cause `ERROR: LoadError: "Indexing into the following expression was not recognized: 1:10"`. This error is not related to this PR and not common, feel free to ignore it, if this is not allowed.
Second, for
```Julia
@turbo for ix in enumerate(A)
A[ix[1]] = ix[1] + ix[2]
end
```
where the index `i` and variable `x` are not unboxed. I tried to generate symbols firstly and regroup them as a tuple like this
```Julia
for ix_ind = Base.OneTo(length(A))
ix_var = A[ix_ind + firstindex(A) - 1]
ix = …
```

feat: replace enumerate

---

docs/src/index.md
docs/src/performance_accuracy.md
docs/src/performance_accuracy_fastmath.md

This draft PR is based on a recent slack thread about the arithmetic transformations and function substitutions performed by `@turbo` and how they affect both accuracy and performance, as well as how they compare to the transformations performed by `@fastmath`. Thanks to @chriselrod and @oscardssmith for the incredibly helpful discussion. It would be great to preserve these insights and make them easy to find for future users. For now, I've copied the discussion verbatim over to a separate page in the docs. Aiming to come back and edit this into prose soon, but maintainers are also welcome to edit freely.

Include discussion of performance vs. accuracy tradeoffs and comparison to fastmath in docs

---

Project.toml
src/broadcast.jl

Locally, this gets everything working with the current master branch of ArrayInterface

Fix contiguous_axis

---

Project.toml
src/codegen/lower_threads.jl
src/condense_loopset.jl

this code wasn't reached anyway, so perhaps it should be removed?

Length of tuple

---

src/LoopVectorization.jl
src/condense_loopset.jl

Without these dispatches, `can_turbo` will return false for the two-arg versions of `trunc`, `unsafe_trunc`, `round`, `ceil`, and `floor`, which follow the form
`f(::Type{T}, ::Union{Base.IEEEFloat, Base.BitInteger64}) where T<:Union{Base.IEEEFloat, Base.BitInteger64}`
These are well-supported in `VectorizationBase`; moreover, the 1-arg versions register as safe despite the recent changes. I have included `convert` and `reinterpret` in this list, as they happen to follow the same form, and are also well-supported.
I happened upon this as I [use](https://github.com/andrewjradcliffe/MarsagliaDiscreteSamplers.jl/blob/5cba2997c8101bc88529d0b9e78d59659715e084/src/generation.jl#L113-L124) `unsafe_trunc` in a Marsaglia sampling method. I had not called said method in while (approx. 1 month), but …

Restore behavior (by declaring safe) of these two-arg functions

---

src/simdfunctionals/map.jl

This lets LoopVectorization work more broadly .. e.g. VectorizedStatistics can process NTuples, `vminimum((1.0,2.0,0.5,1.5))` (currently it chokes).

let homogeneous tuples be `alldense`

---

src/modeling/graphs.jl
src/parse/memory_ops_common.jl

This is based on the following code (on Julia v1.8.3):
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add("FixedPointNumbers"); Pkg.develop("LoopVectorization")
julia> using SnoopCompileCore; invalidations = @snoopr(using LoopVectorization, FixedPointNumbers); using SnoopCompile
julia> length(uinvalidated(invalidations))
613
julia> trees = invalidation_trees(invalidations);
julia> trees[end]
inserting reduce_first(::typeof(Base.add_sum), x::FixedPoint) in FixedPointNumbers at ~/.julia/packages/FixedPointNumbers/HAGk2/src/FixedPointNumbers.jl:295 invalidated:
backedges: 1: superseding reduce_first(::typeof(Base.add_sum), x) in Base at reduce.jl:402 with MethodInstance for Base.reduce_first(::typeof(Base.add_sum), ::Any) (166 children)
julia> ascend(trees[end].backedges[end])
``` …

fix some invalidations caused by FixedPointNumbers

---

Project.toml
src/condense_loopset.jl
test/grouptests.jl
test/manyarrayrefs.jl

This seems to work without causing any extra errors, hopefully CI bears it out.

Use 16 bits to store an array reference index

---

src/constructors.jl
src/modeling/graphs.jl

```
julia> tree
inserting ==(retcode::SciMLBase.ReturnCode.T, s::Symbol) @ SciMLBase ~/.julia/packages/SciMLBase/QqtZA/src/retcodes.jl:348 invalidated:
mt_backedges: 1: signature ==(x, y) @ Base Base.jl:127 (formerly ==(x, y) @ Base Base.jl:127) triggered MethodInstance for MacroTools.store!(::Dict{Any, Any}, ::Symbol, ::Symbol) (3 children)
2: signature ==(x, y) @ Base Base.jl:127 (formerly ==(x, y) @ Base Base.jl:127) triggered MethodInstance for isequal(::Any, ::Symbol) (1 children)
backedges: 1: superseding ==(x, y) @ Base Base.jl:127 with MethodInstance for ==(::Any, ::Symbol) (224 children)
2 mt_cache
```
The plurality of those invalidations are LoopVectorization-related.

Fix invalidations from new `==` method

---

Project.toml
src/LoopVectorization.jl

@ChrisRackauckas no fear
`max_methods=1` can't hurt you if ~~you're pure of heart~~ type stable.

Unconditional max_methods=1

---

README.md

Seems like a couple of words were missing here.

Fix typo in README.md's "Benchmarks" section

---

test/precompile/precompile.jl

This updates for https://github.com/JuliaLang/julia/pull/49071. I added this test, so I thought I should fix it.

Allow for singleton specialization in precompile test

---

src/modeling/determinestrategy.jl
test/gemm.jl

Also, it heuristically doubles the estimated throughput of apple-m*. This check should work regardless of whether running Mac or Linux, as long as the CPU is recognized.
@heltonmc
```julia
julia> function dot_turbo_ls(ca::AbstractVector{Complex{T}}, cb::AbstractVector{Complex{T}}) where {T}
a = reinterpret(reshape, T, ca)
b = reinterpret(reshape, T, cb)
re = zero(T)
im = zero(T)
LoopVectorization.@turbo_debug for i ∈ axes(a, 2)
re += a[1, i] * b[1, i] + a[2, i] * b[2, i]
im += a[1, i] * b[2, i] - a[2, i] * b[1, i]
end
end
dot_turbo_ls (generic function with 1 method)
julia> T = Complex{Float64}; n = 203;
julia> xv = rand(T, n);
julia> yv = rand(T, n);
julia> ls = dot_turbo_ls(xv,yv);
julia> LoopVectorization.choose_order_cost(ls)
rt = 4.5
sl = 12
op = var"##op#307" = …
```

Update throughput and latency cost calc for shuffling reductions

---

README.md
docs/src/getting_started.md

I've added a note that @turbo can not be applied to functions that are passed kwargs and provided an example of how to work around this limitation. Notes are provided in both the `ReadMe.md` and the `getting_started.md`

@turbo function(;kwag) work around

---

Project.toml
src/LoopVectorization.jl

ArrayInterface 7.x, which is already required, switched to using package extensions and removed the ArrayInterfaceCore package.
Get rid of that dependency and use the symbols directly from ArrayInterface instead.
(These two symbols are just aliases of types from other packages which is why this still works right now.)

Remove ArrayInterfaceCore dependency

---

src/condense_loopset.jl

These debug statements were added in https://github.com/JuliaSIMD/LoopVectorization.jl/pull/519. They made CI fail in https://github.com/ranocha/SummationByPartsOperators.jl/pull/241. I think it would be nice to disable them again (or only enable them with a special debug setting?).
It would be nice to get a new release when this is merged.

remove debug statements

---

src/constructors.jl

Error handling if the ci is of type GlobalRef, from which the Expr can be constructed. It also have error handling if the Ci  is a different type.

Fixed Expr issue when the ci is a type of GlobalRef 
